
pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    curl -LO https://julialang-s3.julialang.org/bin/linux/x64/1.1/julia-1.1.1-linux-x86_64.tar.gz
    tar xf julia-1.1.1-linux-x86_64.tar.gz
    rm julia-1.1.1-linux-x86_64.tar.gz
    sudo mv julia-1.1.1 /usr/local/julia
  displayName: 'Download Julia v1.1.1'

- script: |
    sudo apt update
    sudo apt install gfortran cmake
  displayName: 'Install gfortran and cmake'
